name: Build SpikeOS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential grub-pc-bin xorriso

      - name: Build ISO
        run: |
          gcc -ffreestanding -m64 -c kernel.c -o kernel.o
          ld -T linker.ld -o kernel.bin kernel.o
          mkdir -p iso/boot/grub
          cp kernel.bin iso/boot/kernel.bin
          cp grub/grub.cfg iso/boot/grub/grub.cfg
          grub-mkrescue -o spikeos.iso iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: spikeos
          path: spikeos.iso
